### ISSUE TITLE
Deploy script checks for PHP version 7.1, but that should be 7.0

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#146]
Lin (our server that we deploy core to) runs PHP 7.0. But the deploy script checks for version 7.1: https://github.com/freesewing/core/blob/develop/scripts/deploy.sh#L8

That's wrong, and should be updated to be 7.0. It's a 1-character fix in one line of code :)

**Comment by dglaude** [comment]
I hope nothing was relying on new feature or bugfix from [PHP 7.1](http://php.net/manual/en/migration71.php)

**Comment by joostdecock** [comment]
No, we support PHP5.6 and upwards
