### ISSUE TITLE
Sample service cannot sample options of type 'chooseOne' 

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#15]
When sampling options, the sample service can only sample options when it's a numeric range. Things like different ease and so on.
But you can't sample an option where you have a choice between options. Like [number of buttons](https://api.freesewing.org/sample/WahidWaistcoat/options/buttons/) or [hem style](https://api.freesewing.org/sample/WahidWaistcoat/options/hemStyle/).

Perhaps it's worthwhile to make the sample service capable of handling this too.

**Comment by joostdecock** [comment]
Perhaps having the sample service handle these kind of options is too much of a hassle. But it shouldn't be too hard to have it take options on board. 

As an example, you can't override the hemStyle when sampling the WahidWaistcoat ([example](https://api.freesewing.org/sample/WahidWaistcoat/measurements/?samplerGroup=realMen&hemStyle=2)), whereas you can do that in the compare service ([example](https://api.freesewing.org/sample/WahidWaistcoat/measurements/?samplerGroup=realMen&hemStyle=2)).

The compare service does this thanks to @cabi who added this feature. We should port that to the sample service.

**Comment by cabi** [comment]
Hi @joostdecock ,

were this what do you meant?

Greetings,
Carsten

**Comment by joostdecock** [comment]
Yes, thank you. I merged your pull request for this. At least I think I did.  I must have forgotten to close this, so I'll do that now. Thanks again @cabi !
