### ISSUE TITLE
Caveats for migrated model data - fail to get to correct page

### ISSUE THREAD

**Issue by jbs750** [joostdecock/core#157]
I tried to read the "caveats for migrated model data" by clicking on the embedded link.  It fails and takes you to an error page.

**Comment by joostdecock** [comment]
I'll need to update that link. Meanwhile, the page is here: https://dev.freesewing.org/docs/site/makemypattern-migration-caveats:

**Comment by joostdecock** [comment]
FIxed in the data repository: https://github.com/freesewing/data/commit/aea1ff77441f1ebd00ee8e13aa82bb6226802ca3
