### ISSUE TITLE
part.php, shiftTowards

### ISSUE THREAD

**Issue by woutervdub** [joostdecock/core#167]
I found something where the code is not functioning according to the documentation. Not sure if this should be called a bug. Source: `part.php`, function `shiftTowards`.

According to the core API documentation (https://freesewing.org/docs/core/classdocs/src/part#shifttowards), if the distance is negative, the point is shifted away:
> If $distance is negative, we’ll shift away from $direction.

The code actually doesn't do that if both x and y coordinates are different for both points (the line between them is under an angle other than 0, 90, 180 or 270 degrees). It uses an `abs($delta)`, which will always point the new point towards the reference point.

Problem part:
```php
        if ($point1->getX() < $point2->getX() && $point1->getY() > $point2->getY()) {
            $x = $point1->getX() + abs($deltaX);
            $y = $point1->getY() - abs($deltaY);
```
etc.

Test case:
```php
		$p->newPoint('test1', 100, 100, 'Reference' );
		$p->newPoint('test2',  90, 110, 'Start' );
		$p->addPoint('test3', $p->shiftTowards('test2', 'test1', -5), 'NewPoint');
		$p->addPoint('test4', $p->shiftTowards('test2', 'test1', 4), 'NewPoint');
```
`'test3'` and `'test4'` should be on opposing sides of `'test2'`. They are both between `'test1'` and `'test2'`.

I'm not sure what the consequences are of removing the `abs()` function, although testing with this small sample proved correct.

**Comment by joostdecock** [comment]
Well spotted, thank your for reporting this.

As it happens, the documentation needs to be updated. Historically, `shiftTowards()` used to accept negative values.

Later, the `shiftOutwards()` method has been added. Using `shiftTowards()` with negative values has the same effect as using `shiftTowards()` with inverted start- and end-point.

So, `shiftTowards()` has been nerved to no longer handle negative values. This way, designers that want the `shiftOutwards()` behaviour are forced to use `shiftOutwards()`, which make the code more readable/intuitive.

I have updated the documentation, so I'll close this.
