### ISSUE TITLE
Wahid typos

### ISSUE THREAD

**Issue by PD75** [joostdecock/core#173]
[freesewing.wzetf.pdf](https://github.com/freesewing/core/files/1391290/freesewing.wzetf.pdf)

4 - Front lining, says "main fabric" should be "lining"
7 & 8 should switch place bigger bag is the back, visible when one opens a pocket, smaller bag from lining

**Comment by joostdecock** [comment]
Thanks for these corrections @PD75 

I am currently trying to get my new Huey pattern out the door, so I'm going to put a pin in this for now. But I'll pick it up once that's done.

**Comment by joostdecock** [comment]
Thanks for reporting this @PD75 This is fixed in the develop branch, and will be rolled out to the master branch soonish.
