### ISSUE TITLE
Name all parts to keep track

### ISSUE THREAD

**Issue by PD75** [joostdecock/core#174]
I did Theodore and Wahid from same cloth, it was hard time keeping track which was which. Maybe put 
"Wahid - name" in each pattern piece. Like "Wahid - Väst" https://freesewing.org/drafts/wzetf

**Comment by joostdecock** [comment]
Thank you @PD75 that is a good suggestion.

It's probably not very realistic to ask pattern designers to have the discipline to include this every time. So I guess hacking `Pattern::addTitle` to always prefix the title with the pattern name would be the way to go.

If we make it optional, yet enabled by default, we don't need to adapt any patterns.

I am currently trying to get my new Huey pattern out the door, so I'm going to put a pin in this for now. But I'll pick it up once that's done.

**Comment by joostdecock** [comment]
Fixed in the develop branch. Thanks for the suggestion @PD75
