### ISSUE TITLE
Core install seems stuck in composer dependency limbo

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#176]
Subject says it all. Thanks to @jenniferjacobs for reporting this.

**Comment by jenniferjacobs** [comment]
Hi @joostdecock, I've figured this one out. My Mac was running PHP v5.5. I installed Homebrew and updated to 7.1, and that sorts the problem out. I've taken a few notes on how I set up my instance and will make some suggestions to the install instructions for future. Thanks – I think that resolves the issue :)

**Comment by joostdecock** [comment]
Ah, minimal requirement is PHP >= 5.6 (for core) so that explains it.

Ok, so I'm closing this now, you can submit your suggestions for improved install instructions in a pull request.
