### ISSUE TITLE
Prevent pocket opening from getting too narrow when torso on Hugo is short(er)

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#244]
[This draft](https://freesewing.org/drafts/dmvax) has a pocket opening in which a grown man can't fit his hand. That shouldn't happen.

**Comment by woutervdub** [comment]
Draft is private...

**Comment by joostdecock** [comment]
Ah, I'll ask the user to share it.

**Comment by joostdecock** [comment]
Fixed in core v1.11.1
