### ISSUE TITLE
Organise/update translation files

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#25]
While translation is supported, it's not exactly ready for translators to do their thing. Strings are missing from the translation files, while others are repeated in parent/extended patterns.

We need to clean it up and get everything ready so that people with additional languages under their belt can just pick up a language file and translate it.

**Comment by cabi** [comment]
Here my proposal. 
-----------------------

I think we should use a scope and fallback system for the localization.
Some of these things are already implemented (as far as I can see).

Pattern
======
* all Pattern translations that used in near to every Pattern like 'cut on fold'
* I think, every Pattern instantiate this class

{Pattern}
======
* all Pattern specific translations like 'Waistband'

Languages
=========
* a fallback system
* en is the default language (I presume)
* all other languages will be an overlay
* so if a language is switched on in the pattern all text will be loaded in en and if there is a translation in fr it will replace the default value.

Optional
=======
* I don't know how far _fso_ will be come, so we can also start with a 'ISO-3166 Country Codes and ISO-639-1 Language Codes' localization. like the locales in our systems (examples: de_BE, de_DE, nl_NL)

Todo
====
As a first step is to dump all **en** variables to the EN-files. This will be a good start for our translations.

**Comment by joostdecock** [comment]
That sounds sensible :+1:  And I think most of this is already there.
I had started to move translations that are pattern agnostic into the Pattern file, but when I wanted to do that for German, my vim did not display the umlauds properly.
Which led me down a rabbithole of trying to get it to behave because my bash does support it, but somehow vim won't.

Anyway, I will stick to rearranging the English for now.

Not sure about the country+language stuff. Perhaps later?

**Comment by cabi** [comment]
... maybe this is a ready forged and working component?
http://symfony.com/doc/current/translation.html

I think it had all we need and we can easy replace the current system without great hassle.

**Comment by cabi** [comment]
> We're already using that ;)
> Check here: https://github.com/joostdecock/fso/blob/develop/src/Context/Context.php#L291

Nice :+1: 

OK, I will look in the german translations. I tried it a bit for  the AaronShirt lately.

**Comment by joostdecock** [comment]
[I got a few commits mixed up, so I removed some comments here where I linked to them]

We're already using that ;)
Check here: https://github.com/joostdecock/fso/blob/develop/src/Context/Context.php#L291
I think we need nothing new. Both languages are loaded, if the one we want is not avaialable, we fall back to what is defines as locale in the config file.

We just need to organise the translation files themselves a bit. I have done so for the Pattern class (it now has all strings that are pattern-agnostic in EN and NL. It would be nice if @cabi could do DE.

And I've cleaned up the translation files for AaronAshirt (also EN and NL) so that it has only the pattern specific strings.
We should do the same for other patterns, but first, lunch :)

Also, maybe we should look into some sort of tool to help translators. Because this gets confusing (or is that just me?)

**Comment by cabi** [comment]
Translations and localizations are always confusing. Wait for arabic translations with a RightToLeft textflow. :8ball: And then mix 'normal' english text in it. :hammer: 

If the places of the files and their function documented and described - I think it is relativ simple to create a new localization.

**Comment by joostdecock** [comment]
Hey, there's a translation file in the theme too. 
If you want, you can do the German version of https://github.com/joostdecock/fso/blob/develop/themes/Theme/translations/messages.en.yml

**Comment by joostdecock** [comment]
I think we're done. There's still translations missing (we don't have a DE file everywhere) but that's an ongoing struggle.

For info, this is the current list of translation files:

```
git ls-files | grep messages.
patterns/AaronAshirt/translations/messages.de.yml
patterns/AaronAshirt/translations/messages.en.yml
patterns/AaronAshirt/translations/messages.nl.yml
patterns/CathrinCorset/translations/messages.en.yml
patterns/CathrinCorset/translations/messages.nl.yml
patterns/HugoHoodie/translations/messages.en.yml
patterns/HugoHoodie/translations/messages.nl.yml
patterns/JoostBodyBlock/translations/messages.en.yml
patterns/JoostBodyBlock/translations/messages.nl.yml
patterns/Pattern/translations/messages.de.yml
patterns/Pattern/translations/messages.en.yml
patterns/Pattern/translations/messages.nl.yml
patterns/TrayvonTie/translations/messages.en.yml
patterns/TrayvonTie/translations/messages.nl.yml
themes/Theme/translations/messages.en.yml
themes/Theme/translations/messages.nl.yml
```

**Comment by cabi** [comment]
themes/Theme/translations/messages.de.yml
