### ISSUE TITLE
Provide French translations

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#33]
@cloutiy volunteered to add French translation, so this issue is for him.

To add a translation, you'll need to copy the English language file of each pattern to a French file.
These are the current files:

```
patterns/AaronAshirt/translations/messages.en.yml
patterns/CathrinCorset/translations/messages.en.yml
patterns/HugoHoodie/translations/messages.en.yml
patterns/JoostBodyBlock/translations/messages.en.yml
patterns/Pattern/translations/messages.en.yml
patterns/TrayvonTie/translations/messages.en.yml
themes/Theme/translations/messages.en.yml
```

To get a list like this, run: `git ls-files | grep messages.en.yml`

Copy messages.en.yml to messages.fr.yml, and translate them.
You don't have to translate the keys, just the values.
For example, this:

"Back": "Back"

in the messages.en.yml file should become something like:

"Back": "Dos"

in the messages.fr.yml file.

Note that apart from patterns, the Theme class also has a translation file.

Last but not least, once the translation is there, you'll need to add the language to the config.yml file of the pattern for the system to make it available as a language.

If you have any questions: shoot!

**Comment by cloutiy** [comment]
1. Translations have been uploaded for all except: Bruce Boxer Briefs, Tamiko Top, Wahid Waistcoat 
patterns/AaronAshirt/translations/messages.fr.yml
patterns/CathrinCorset/translations/messages.fr.yml
patterns/HugoHoodie/translations/messages.fr.yml
patterns/JoostBodyBlock/translations/messages.fr.yml
patterns/Pattern/translations/messages.fr.yml
patterns/TrayvonTie/translations/messages.fr.yml
themes/Theme/translations/messages.fr.yml

2. Added fr: French for their config.yml

**Comment by cloutiy** [comment]
Will close this issue. A new issue can be created once Bruce Boxer Briefs, Tamiko Topand Wahid Waistcoat are ready for translation.
