### ISSUE TITLE
Do we need a router/dispatcher overhaul? And what would that look like?

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#35]
@straytaoist waxed lyrically in #34 about _a nice clean, definable API_ thanks to some dispatcher magic, and now that's all we can think of.

I'm creating this ticket so its openness will be a nagging reminder that this shit ain't going to dispatch itself.

**Comment by straytaoist** [comment]
Heh, as soon as my Christmas-food-coma is over, I'll wax lyrical again :)

**Comment by straytaoist** [comment]
Good evening everyone.

OK, so here is what I mean by a dispatcher, what Modern Kids(tm) call a router. Here is an entire webserver, I'll break it down in a sec:

https://gist.github.com/straytaoist/01da4318cf0dbd8afe4525ac5e6add0f

Now, if you want to see it in action, that is running on my awesome scaleway box. Hit it all you want:

http://163.172.176.177:8118
A simple homepage

http://163.172.176.177:8118/healthcheck
A simple health check, returns a 200, so I know the server is still up

http://163.172.176.177:8118/named/hello
And lo, a REST path. Changing 'hello' is allowed. That is what goes into the 'named_param' that is extracted by ByName().

http://163.172.176.177:8118/sfsdf
A 404. I didn't bother writing a 404 page.

So the guts of it really is:

 router.GET("/", homepage)
 router.GET("/health", healthCheck)
 router.GET("/named/:named_param", named)

You have a path, and a method it dispatches to. And yes, you can have any http verb: POST/DELETE/PUT whatever. I've written three simple GETs, because this is just an example.

Now, if I was actually doing this properly, I'd have this in a not-main namespace, and the functions in a file of their own, but that is neither here nor there for the time being. The point is, I like a dispatch table as I can kinda see what is going on.

I should point out that golang is *not* an OO language, either. (That also said, I am loving golang, it is a really lovely language.)

For old people like me, a list of valid paths (build up your REST API here!) makes it easier to see what is going on. And you get the whole separation of HTML from logic, template things away if you want. Plus I get a nice binary I can run on my own server, logging how I want it and all the other nice things I didn't add in the three minutes it took me to write that there. (See? An entire webserver, locked down to only the paths I wanted to create, in three minutes. :) I make a lot of these to do things for me, all on different ports (there is a telescope binary that does sky calculations for me, I've a dna system that helps local researchers into Parkinson's, various radio ham APIs, Quantified Self APIs, yadayada. They are cheap and easy to knock together using that pattern. Router->methods. Job done.

BUT I am not advocating any of this, this is the way *I* tend to do things, as it is the way *my* brain works.

Comments/discussions welcome. I love to share/learn, and be told I'm wrong. As then I know, and next time, I'll be right. What is the point in me being wrong if I can be right, eh?

**Comment by cabi** [comment]
I know what you mean and there are many ways to do this under PHP :)
As example - on base of the slim-framework (https://www.slimframework.com/):

```
<?php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;

require 'vendor/autoload.php';

$app = new \Slim\App;
$app->get('/hello/{name}', function (Request $request, Response $response) {
    $name = $request->getAttribute('name');
    $response->getBody()->write("Hello, $name");

    return $response;
});
$app->run();
```

This can be extended with a controller/action logic ... :)

**Comment by joostdecock** [comment]
Thanks for your input guys. I don't have strong opinions on the matter (although I must say that from my exposure to it, I do like golang, and I found @straytaoist example very elegant), but I will share my thoughts on the matter.

**Must PHP Go?**

This is currently a PHP project. A choice that has its advantages and inconveniences. I could defend my choice for PHP, but I don't feel that choice is under attack. Instead, I will assure @straytaoist that he is not wrong. The way he does things is elegant, and particularly well suited for some RESTful API.

That being said, I am not looking forward to porting this project to Golang. And given that we would be doing it merely because the routing would be more elegant (and not because it would make our patterns so much better) I'm going to say that for the time being, PHP is here to stay.

**Who does what, and who needs a webserver anyway?**

In @straytaoist 's example, all routing is handled in the code -> neat. That is possible because the code is also the webserver.

In PHP, we're going to be dealing with a webserver. And that's where routing happens. 

What we can do is minimize the routing logic in the webserver, and shift it to our script. In other words, tell Apache or whatever to let index.php handle everything, and then fan out the different options in our code.

[Symphony](http://symfony.com/) (the PHP framework from which we already use the autoloader, translator, and YAML file handler) has [a routing component](http://symfony.com/doc/current/routing.html). I don't know if @cabi has any experience with it?

We could use this component to handle the routingin our code, but we would still be dependent on URL rewriting by the webserver (even if it's just one rule to send everything to index.php), because that sits lower on the stack.

**Conclusion**

I guess my question is that given that:

- we are using PHP and webserver
- to get clean URLs, we are depending on webserver URL rewriting

Do you still consider a routing overhaul to be needed? Given that (at least from where I stand) Golang's clean URL nirvana is out of reach in PHP.

**Comment by cabi** [comment]
I don't think that @straytaoist suggestion is to change to golang. He use the code as an example for routing and dispatching. This is what I understand.
If I use php in serve-mode than it is possible to do similar route-things without webserver - not neat as in golang ... but similar.

I like the MVC structure given by frameworks - it makes things a lot easier to maintain.
But if we build our own framework, use symfony or silex (the small symfony) ... a least we have to have a plan. :)

**Comment by joostdecock** [comment]
I don't think we're changing to golang either :) 
The point I was trying to make is that this code will typically run within a webserver, and so we have less options for routing than in the golang example.

We can still move to a framework for routing or we can look at MVC. I understand that the current front controller approach is inelegant, and I would love to see improvements in this domain.

I don't really have much experience with this. So please take all my input with a pinch of salt.
However, my preference would be to use the Symfony framework because we're already using it.

And, if we are serious about this, and want to adopt routing + MVC, this is going to be a rather substantial change. One that I can't do on my own.

But if you guys are up for it, let's do it.

**Comment by straytaoist** [comment]
Just to be Devil's Advocate here...why the hangup on MVC? Sometimes that separation doesn't make much sense (to me). So a bit of hand-waving...

1. There is a webserver that 'routes' (however it does it, rewrite rules whatever) a set of parameters somewhere that does something

or

2. There is a webserver that takes form data, turns it into (say) JSON and dispatches that off somewhere to be processed, and returns some SVG.

The point being, neither is MVC. And indeed the engine (where things get sent to be processed) doesn't even need to be...in the web system. It can be a binary, or whatever.

All I want to say it not to get caught up in thinking MVC, as then...you think MVC and structure things accordingly. One of my favourite sayings these days is that 'people never ask the right questions'. (Not having a go at anyone _here_, just saying. I mean, all the work here is ace. And best of all, the main thing, it works. My motto tends to be: make it work. Everything else can come after.)

I mean, I might play about for fun, without ripping the thing apart. Consider:

(a) a nice little simple golang webeserver
(b) that uses the already-there-and-work forms
(c) but takes the form input, converts it to JSON and dispatches somewhere
(d) that just calls the existing PHP to do pattern things
(e) that returns SVG to another route in the golang
(f) that displays the requested pattern

Now what we have is separation. The routing (ok, so it doesn't have to be golang ;) lives on its own, and doesn't concern itself with anything other than handling the input and converting to something nice to send along elsewhere. Then there is the fso 'engine', that gets fed input, generates the pattern and sends it back to be rendered.

And if someone makes the PHP faster/better, there is no knock-on elsewhere. And if someone invents an new language for the routing and it is better, you replace that. (OK, so I was thinking here you could dockerise all the things: the router/webserver in a container, that talks to another container that is only the pattern engine...why yes, I have been drinking, what are you implying?)

(And as this is more a discussion thread, sure we can run with it :)

And if we do eventually separate out, then you have a clean API that you don't even need to use in a browser, I could call it direct from the command line. A nice REST call using curl.

The steps to this place aren't hard, the main thing is the separation. No muddying of the engine with the dispatcher/rewrite rules. Meantime, I'll have a look at this Symphony, and teach myself some PHP.

**Comment by joostdecock** [comment]
The problem I see with building a fully separated containerized thing that builds on a bunch of technologies, is that there's no use case for that.

Sure, when I get freesewing.org up and running to replace makemypattern.com, I could tap into all that awesomeness. But part of the reason I'm releasing this as open source is to allow pattern designers to run their own instance. 

So that means that

- We are not building a public API
- I'd like it to remain within reach of the ambitious web boy/girl to get this up and running

There's a reason this is written in PHP. And that reason (apart from the obvious that I am familiar with it) is that it's the language that powers just about every pattern company/designers/sewing enthusiasts website out there.

These people may not be PHP gurus, but they probably know how to change a theme, and perhaps have even mucked about in the PHP code just a bit. Perhaps more importantly, their hosting plan does support PHP. And this software project can run (in principle) on a webserver to which you only have FTP/SCP access. Just a tarball that you drop in a web-accessible directory, and _it works_.

Imagine some pattern designer. She (yes, I made her female) has a day job, but on the site she designs sewing patterns that she sells on her website. That website runs on Wordpress, and the shop is powered by Shopify.

I think this person can totally run this thing, if she wanted to. But I don't think she is going to be running a standalone gloang deamon or a bunch of docker containers. That's just scary.

As much as I'd love to have a docker image available for this thing, that one can just run. I'd rather not have it as a requirement.


Now with that out of the way, I have a question:

> (a) a nice little simple golang webeserver
> (b) that uses the already-there-and-work forms
> (c) but takes the form input, converts it to JSON and dispatches somewhere
> (d) that just calls the existing PHP to do pattern things
> (e) that returns SVG to another route in the golang
> (f) that displays the requested pattern

What is the added value of the golang webserver?

There are no already-there-and-work forms. Do you mean the demo? That's just an example.
Whoever builds a frontend for this can submit their form in JSON. And the channel can handle that input and turn it into what we expect. Or don't submit the form in JSON, as you wish. It's your channel and you can set it up as you want.
Want curl? That works too.

And once we have the SVG, we're pushing it to the browser. Or not. In the developer theme, we make it part of a JSON response, and return that. It's up to the theme to decide how we handle that.

So I do think we have a lot of flexibility already. I agree that it's not exactly super clear what gets routed where without a deeper look into the code. Something that perhaps a routing component might fix.

But apart from that, the abstraction you outline seems to add a lot of complexity for little gain. And (this is my main gripe) it would significantly extend the requirements to run this thing. 

Now I need to go looking for a picture of a seal or something, because I'm aware of how I can sound ;)

**Comment by straytaoist** [comment]
No benefit in the golang server, it is more the separation of concerns. Which is what I always thought MVC was supposed to do, before the weenies came along and muddied the waters.

And when I said forms, I meant messages. Which go to your channels. I guess I find it a bit...obfuscated right now, and need to code-dive. (Disclaimer: I started life as an assembly coder, worked in compilers for years, and being a *ix person forever, like separation, and one tool doing one thing. I am a simple sort.)

Funny I don't see the separation as 'complexity'. (Then again, another disclaimer, as a recovering astrophysicist complex means something entirely different. Adding 15-digit numbers together is complex, but simple. Yadayada.)

Whenever something isn't easy to grok how it works from the off, I like to realign things so it is. (Last disclaimer for now: I am not anyone's target demographic, and also took too many philosophy courses, and like to discuss profusely in pubs. Come join me some time :)

I don't know enough about wordpress/shopify/php to know how these things hang for a super-creative evening-pattern-making young lady, but yeah, ease of install/use is paramount. But then, so it making it easy to extend for code jockeys. (I did install Movable Type years ago, and indeed, my erstwhile weblog runs of it. That became WordPress I think?)

Anyhow, yes, this thread was supposed to just be pie-in-the-sky stuff, and fun. I'll probably use a picture of my dog next time 🐶

**Comment by joostdecock** [comment]
Of course, the philosophy courses. This all makes sense now :)

I am a pragmatic who wants to ship something. But I also feel we need to make it easy for developers to jump in. So some effort is needed.

Should we perhaps look at `[Silex](http://silex.sensiolabs.org/)`? 

@cabi, you are the most experience PHP developer. What do you suggest?

**Comment by joostdecock** [comment]
I'm closing this because life is short.
