### ISSUE TITLE
Create compare service (sample + draft)

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#4]
A problem with my current implementation is that people put it incorrect measurements or silly options for values. They end up with a pattern that is bonkers, but in the absence of something to compare it to, they don't realize that.

I'd like to add a service (in addition to draft/sample/info) services that does what the sample service does (draft the pattern in different sizes), and adds the user's pattern (styled diffferently with CSS).

This way, you can see how your pattern compares to what is expected, and where if differs in unexpected way.

**Comment by cabi** [comment]
Hi,

in the CompareService-Branch I implement a first try to compare the different measurements.
I used here the sampleService as base and add the possibility to add a custom user-measurement.
The drawing shows now the group-models and the user-model. 
URL to test (with one wrong size) :  http://fso.local.de/compare/HugoHoodie/measurements/?samplerGroup=maleStandardUsSizes&acrossBack=45&bicepsCircumference=53.5&centerBackNeckToWaist=48&chestCircumference=108&naturalWaistToHip=12&neckCircumference=42&shoulderLength=16&shoulderSlope=4&hipsCircumference=95&sleeveLengthToWrist=70&wristCircumference=19&headCircumference=59&chestEase=3&bicepsEase=3&cuffEase=4.5&ribbingStretchFactor=85&theme=Svg&lang=en&unitsIn=metric&unitsOut=metric

Todos:
* differentiate the userModel from the exampleModels (I'm not so firm with svg)
* integrate the compare to the docs

Greetings,
Carsten

**Comment by joostdecock** [comment]
This is great work. I've added a theme for the compare service. It's empty (from a logic point of vierw) but does have some custom CSS to style the compare output.

I've ripped out the options mode in the CompareService class, since (at least for now) we're only comparing measurements.

Talking about options, the compare service loads the default options for all models. It would be cool if we could apply the user-submitted options to all models. 
Currently we call Sampler->loadPatternOptions() which loads options from the pattern config. What we should perhaps do instead is call Channel->standardizePatternOptions()

**Comment by joostdecock** [comment]
Also: I will do the frontend integration for the demo. I'm leaving the option loading to you, if you want it.
Just so we stay out of each other's hair now that I'm messing on your branch @cabi :)

**Comment by cabi** [comment]
Hi @joostdecock,

I added the options to the CompareService. I hope that I did it in the right way. 
It looks like that all models now respect my 'ease' changes.

**Comment by joostdecock** [comment]
Perfection :+1: 
I've added the compare service to the demo. So I think we can merge this in develop?

**Comment by cabi** [comment]
Yes ... if the result as wanted. :)
Then you can merge it and we close this branch.
Nice!
