### ISSUE TITLE
Make buttonholes on WahidWaistcoat horizontal

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#42]
Buttonholes on a waistcoat should be horizontal. They are currently vertical (the default when inserting the buttonhole snippet).

The buttonholes are added in [lines 374, 377, and 379 of WahidWaistcoat.php](https://github.com/joostdecock/fso/blob/develop/patterns/WahidWaistcoat/WahidWaistcoat.php#L374).

To rotate the buttonhole (or any snippet for that matter) you have to pass an array of attributes as an extra parameter. Use the `transform` attribute and a value of `rotate( degrees xOrigin yOrigin) `as value. More info: https://developer.mozilla.org/en/docs/Web/SVG/Attribute/transform

`degrees` is 90, whereas you should set `xOrigin` and `yOrigin` to the X and Y coordinates of the point where you're inserting the snippet. This way the buttonhole will rotate around it's own mid-point, and thus stay in place.

If you need to cheat, there's a rotated buttonhole [in the SimonShirt collarstand](https://github.com/joostdecock/fso/commit/79d1a653c54933010eb03ffdd589d48b5e96e30c#diff-83d92dd13fb962c4d75381729a4c5598R904)

**Comment by woutervdub** [comment]
Completed.

Added transform to the three lines.
