### ISSUE TITLE
Add check for curvelength before spreading out double sleeve notchesin SimonShirt

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#49]
See https://github.com/joostdecock/fso/commit/521eeea908c8b6596a5b68d6281466d33f76f16d#diff-83d92dd13fb962c4d75381729a4c5598R1822

**Comment by joostdecock** [comment]
ok, so here's what needs to happen. You need to check that the value of $shift+1.5 is not longer than curveLen().
If it is, you need to do some evasive measures. More precisely, you need to shift the notch to the next curve.

**Comment by joostdecock** [comment]
Also, note that this is only available on the simonPaperless branch for now

**Comment by joostdecock** [comment]
Update: this is now available in develop (since a few days actually)

**Comment by woutervdub** [comment]
Haven't been able to look at this in any detail. Been really busy at work and will be for the next week at least. I do intend to get to it eventually...

**Comment by joostdecock** [comment]
Don't worry about it. The worst that can happen is that somebody else fixes it 😉
