### ISSUE TITLE
Boxer pattern improvements

### ISSUE THREAD

**Issue by joostdecock** [joostdecock/core#7]
- Side seams do not match
- The rise is not taken into account properly

**Comment by Stefan1960** [comment]
Here is what I discovered when trying to somehow systematically encircle the issues, where some rework seems to be desireable:

Basic measures (all four pattern options ”waist elastic width”, “speedo rise”, ”negative ease horizontal” and “negative ease vertical“ set to zero for excluding secondary influences):
-	waistline seam length sum of parts #1, #2 and #3 are equal to the entire trouser waist circumference seam length. This looks okay.
-	leg circumference  seam length sum of front parts #1, #3 and #3 are equal to the entire uppermost leg circumference. This looks okay.
-	longitudinal seam length sum of front parts #2 and #4 fit longitudinal seam length. This looks okay. 
-	longitudinal seam length of both #3 and #2+#4 are in my case roughly 33mm shorter than longitudinal seam length of back part #1. No idea why, but that’s no good.
-	curved seams of front parts #2 and #4: short sections from notch to corner fit with each other => okay. Long sections from notch to corner:  #4 seam section is roughly 2cm longer than #2 seam section and should be shortened.
-	Crotch seam of Back part #1: Distance of the two side notches to the central notch is roughly 1cm larger than corresponding width of front part #2 “tails”. In part #1 side notches should be moved closer to the central notch. After such movement, the remainder of #1 crotch seam (side notch to corner) is still approx. 2cm shorter than corresponding seam length of insert #4. Seam length of insert #4 should be shortened accordingly.

Processed measures:
-	negative horizontal ease leads to an exactly corresponding reduction of entire waistline seam length sum. This is okay.
-	negative vertical ease is difficult to verify on the present diagonal seams, but generally looks quite okay / plausible.
-	increasing ”waist elastic width” from zero to a real value, exemplary 4cm does not as expected just cut off the respective width from related parts #1, #2 and #3. It is rather that said parts are vertically “compressed” in their entirety. The vertical measure from #1 central crotch seam notch to central waist notch is reduced by said 4cm, which is fine. However, such “compressing” approach leads to weird side effects such as: crotch seam length is reduced by approx. 1 cm, curved seams of Front #2 are altered, and so forth. What has all that to do witch elastic band width? I think the entire approach of introducing waist elastic width should be reconsidered.
-	increasing ”speedo rise” from zero to a real value, exemplary 4cm, does only affect parts #2 and #4, not parts #1 and #3. As with the elastic width, the effect of speedo rise on parts #2 and #4 has some unexpected side effects on the lower curved seams. Rework is required.

General design:
-	I don’t think it’s a pattern generation issue but a design issue, which might be incorporated into the pattern: The front should have less height than the back. On my RTW underpants I measured that the elastic is 4cm lower in the front as compared to the back. I had to correct my BoxerBriefs the same way, until they acceptably fit. It looks as if the design should not rely on a straight top line of parts #1, 2 and #3, but might rather go for a nicely curved line for lowering the elastic position in the front.

Hope this helps,
Stefan
